# Generated by Django 4.1 on 2022-08-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vaccines',
            new_name='Vaccine',
        ),
    ]
